[project]
name = "hotel-system"
version = "0.1"
requires-python = ">=3.8"
authors = [
  {name = "Ali Rahimi", email = "ali.rahimi.officalbiz@gmail.com"}
]
description = "a hotel management system that is scalable."
readme = "README.md"
license = ""
